<?php if ($this->form) : ?>
<h1><?php echo $this->escape($this->title); ?></h1>

<?php 
if ($this->messages) {
   $messages = implode("<br />", $this->messages);
   $class = "info";
   if(strstr($messages, 'error')) {
       $class = "error";
   }
   echo '<div class="'. $class.'">'.$messages. '</div>';
}

?>

<?php echo $this->form; ?>

<p id="loggedin">Logged in as <a target="_blank" href="http://www.twitter.com/<?php echo $this->escape($this->name); ?>"><?php echo $this->escape($this->name); ?></a>. <a href="<?php echo $this->url(array('action'=>'logout'));?>">Logout</a></p>

<?php else : // Not logged in ?>
<br/>You must log into twitter first as Tweets doesn't want to know your username or password!</p>
<p><a href="<?php echo $this->url(array('action'=>'login'));?>"><img src="<?php echo $this->baseUrl() ?>/img/Sign-in-with-Twitter-darker.png" /></a></p>

<?php endif;?>



<a href="<?php echo $this->url(array("action"=>"lottery")); ?>">Lottery start</a>         